
CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

CREATE TABLE "Contributions" (
    "ContributionId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserAgent" text NULL,
    "Distance" integer NOT NULL,
    "TimeStampStart" timestamp with time zone NOT NULL,
    "TimeStampStop" timestamp with time zone NOT NULL,
    "Duration" integer NOT NULL,
    "PointsGeom" bytea NULL,
    "PointsTime" timestamp with time zone[] NULL,
    CONSTRAINT "PK_Contributions" PRIMARY KEY ("ContributionId")
);

CREATE TABLE "Users" (
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserIdentifier" uuid NOT NULL,
    "Provider" text NULL,
    "ProviderUser" text NULL,
    "AccessToken" text NULL,
    "RefreshToken" text NULL,
    "TokenCreationDate" timestamp without time zone NOT NULL,
    "ExpiresAt" integer NOT NULL,
    "ExpiresIn" integer NOT NULL,
    "IsHistoryFetched" boolean NOT NULL,
    CONSTRAINT "PK_Users" PRIMARY KEY ("Id")
);

CREATE TABLE "UserContributions" (
    "UserContributionId" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ContributionId" integer NOT NULL,
    CONSTRAINT "PK_UserContributions" PRIMARY KEY ("UserContributionId"),
    CONSTRAINT "FK_UserContributions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_UserContributions_UserId" ON "UserContributions" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20200722110932_InitialDb', '3.1.5');


