--
-- PostgreSQL database dump
--

-- Dumped from database version 12.3
-- Dumped by pg_dump version 12.4 (Ubuntu 12.4-1.pgdg18.04+1)

-- Started on 2020-09-10 15:28:06 CEST

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 2 (class 3079 OID 2585865)
-- Name: postgis; Type: EXTENSION; Schema: -; Owner: -
--

CREATE EXTENSION IF NOT EXISTS postgis WITH SCHEMA public;


SET default_table_access_method = heap;

--
-- TOC entry 205 (class 1259 OID 2118658)
-- Name: Contributions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Contributions" (
    "ContributionId" integer NOT NULL,
    "UserAgent" text,
    "Distance" integer NOT NULL,
    "TimeStampStart" timestamp with time zone NOT NULL,
    "TimeStampStop" timestamp with time zone NOT NULL,
    "Duration" integer NOT NULL,
    "PointsTime" timestamp with time zone[],
    "PointsGeom" public.geometry
);


--
-- TOC entry 204 (class 1259 OID 2118656)
-- Name: Contributions_ContributionId_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Contributions" ALTER COLUMN "ContributionId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Contributions_ContributionId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 209 (class 1259 OID 2118678)
-- Name: UserContributions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."UserContributions" (
    "UserContributionId" integer NOT NULL,
    "UserId" integer NOT NULL,
    "ContributionId" integer NOT NULL
);


--
-- TOC entry 208 (class 1259 OID 2118676)
-- Name: UserContributions_UserContributionId_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."UserContributions" ALTER COLUMN "UserContributionId" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."UserContributions_UserContributionId_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 207 (class 1259 OID 2118668)
-- Name: Users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."Users" (
    "Id" integer NOT NULL,
    "UserIdentifier" uuid NOT NULL,
    "Provider" text,
    "ProviderUser" text,
    "AccessToken" text,
    "RefreshToken" text,
    "TokenCreationDate" timestamp without time zone NOT NULL,
    "ExpiresAt" integer NOT NULL,
    "ExpiresIn" integer NOT NULL,
    "IsHistoryFetched" boolean NOT NULL
);


--
-- TOC entry 206 (class 1259 OID 2118666)
-- Name: Users_Id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."Users" ALTER COLUMN "Id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."Users_Id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 203 (class 1259 OID 2118651)
-- Name: __EFMigrationsHistory; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL
);


--
-- TOC entry 5251 (class 2606 OID 2118665)
-- Name: Contributions PK_Contributions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Contributions"
    ADD CONSTRAINT "PK_Contributions" PRIMARY KEY ("ContributionId");


--
-- TOC entry 5257 (class 2606 OID 2118682)
-- Name: UserContributions PK_UserContributions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserContributions"
    ADD CONSTRAINT "PK_UserContributions" PRIMARY KEY ("UserContributionId");


--
-- TOC entry 5254 (class 2606 OID 2118675)
-- Name: Users PK_Users; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."Users"
    ADD CONSTRAINT "PK_Users" PRIMARY KEY ("Id");


--
-- TOC entry 5249 (class 2606 OID 2118655)
-- Name: __EFMigrationsHistory PK___EFMigrationsHistory; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."__EFMigrationsHistory"
    ADD CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId");


--
-- TOC entry 5255 (class 1259 OID 2118688)
-- Name: IX_UserContributions_UserId; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX "IX_UserContributions_UserId" ON public."UserContributions" USING btree ("UserId");


--
-- TOC entry 5252 (class 1259 OID 2845298)
-- Name: idx_contributions_pointsgeom; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_contributions_pointsgeom ON public."Contributions" USING gist ("PointsGeom");


--
-- TOC entry 5260 (class 2606 OID 2118683)
-- Name: UserContributions FK_UserContributions_Users_UserId; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."UserContributions"
    ADD CONSTRAINT "FK_UserContributions_Users_UserId" FOREIGN KEY ("UserId") REFERENCES public."Users"("Id") ON DELETE CASCADE;


-- Completed on 2020-09-10 15:48:05 CEST

--
-- PostgreSQL database dump complete
--

